# Generated by Django 2.0.4 on 2018-04-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishfood',
            name='category',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='dish_category', to='food.Category'),
        ),
    ]
