# Generated by Django 2.0.4 on 2018-04-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_dishfood_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlistfood',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='listitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
