# Generated by Django 2.0.4 on 2018-04-12 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20180412_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishfood',
            name='category',
        ),
        migrations.AddField(
            model_name='dishfood',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_category', to='food.Category'),
        ),
    ]
